#!/bin/sh

emoji=$(cut -d ';' -f1 ~/.local/share/emoji.txt | dmenu -i -c -l 15 -p "Emoji:" | sed "s/ .*//" | tr -d '\n')

[ -z "$emoji" ] && exit

printf "$emoji" | xclip -selection clipboard
notify-send "'$emoji' copied to clipboard"
